//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParadoxSaveUtils.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ParadoxSaveUtils.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Clean 的本地化字符串。
        /// </summary>
        internal static string BTN_CLEAN {
            get {
                return ResourceManager.GetString("BTN_CLEAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Peek
        /// 的本地化字符串。
        /// </summary>
        internal static string BTN_PEEK {
            get {
                return ResourceManager.GetString("BTN_PEEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pop 的本地化字符串。
        /// </summary>
        internal static string BTN_POP {
            get {
                return ResourceManager.GetString("BTN_POP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Push 的本地化字符串。
        /// </summary>
        internal static string BTN_PUSH {
            get {
                return ResourceManager.GetString("BTN_PUSH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restart Game 的本地化字符串。
        /// </summary>
        internal static string BTN_REBOOT {
            get {
                return ResourceManager.GetString("BTN_REBOOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Game: 的本地化字符串。
        /// </summary>
        internal static string SELECT_GAME {
            get {
                return ResourceManager.GetString("SELECT_GAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Save: 的本地化字符串。
        /// </summary>
        internal static string SELECT_SAVE {
            get {
                return ResourceManager.GetString("SELECT_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Version: 的本地化字符串。
        /// </summary>
        internal static string SELECT_VERSION {
            get {
                return ResourceManager.GetString("SELECT_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paradox Ironman Savior 的本地化字符串。
        /// </summary>
        internal static string WINDOW_TITLE {
            get {
                return ResourceManager.GetString("WINDOW_TITLE", resourceCulture);
            }
        }
    }
}
